//
//  ListOrdersViewController.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/27/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersDisplayLogic: class
{
  func displaySomething(viewModel: ListOrders.FetchOrders.ViewModel)
}

class ListOrdersViewController: UIViewController, ListOrdersDisplayLogic
{
  var interactor: ListOrdersBusinessLogic?
  var router: (NSObjectProtocol & ListOrdersRoutingLogic & ListOrdersDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ListOrdersInteractor()
    let presenter = ListOrdersPresenter()
    let router = ListOrdersRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchOrdersOnLoad()
  }
  
  // MARK: Want to do something
  
  func fetchOrdersOnLoad()
  {
    let request = ListOrders.FetchOrders.Request()
    interactor?.fetchOrders(request)
  }
  
  // MARK: Display Something
  
  func displaySomething(viewModel: ListOrders.FetchOrders.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
