//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/27/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
  func fetchOrders(_ request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: ListOrdersPresentationLogic?
  var worker: ListOrdersWorker?
  
  // MARK: Fetch Orders
  
  func fetchOrders(_ request: ListOrders.FetchOrders.Request)
  {
    let response = ListOrders.FetchOrders.Response()
    presenter?.presentSomething(response: response)
  }
}
