//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/27/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
  func fetchOrders(_ request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
  var orders: [Order]? { get }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: ListOrdersPresentationLogic?
  var worker = OrdersWorker(ordersStore: OrdersMemStore())
  var orders: [Order]?
  
  // MARK: Fetch Orders
  
  func fetchOrders(_ request: ListOrders.FetchOrders.Request)
  {
    worker.fetchOrders { (orders) in
      self.orders = orders
      let response = ListOrders.FetchOrders.Response(orders: orders)
      self.presenter?.presentFetchedOrders(response: response)
    }
  }
}
