//
//  CreateOrderViewController.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/25/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderDisplayLogic: class
{
  func displayExpirationDate(_ viewModel: CreateOrder.FormatExpirationDate.ViewModel)
}

class CreateOrderViewController: UITableViewController, CreateOrderDisplayLogic
{
  var interactor: CreateOrderBusinessLogic?
  var router: (NSObjectProtocol & CreateOrderRoutingLogic & CreateOrderDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CreateOrderInteractor()
    let presenter = CreateOrderPresenter()
    let router = CreateOrderRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    configurePickers()
  }
  
  func configurePickers() {
    shippingMethodTextfield.inputView = shippingMethodPicker
    expirationDateTextfield.inputView = expirationDatePicker
  }
  
  // MARK: Text fields
  
  @IBOutlet var textFields: [UITextField]!
  
  // MARK: Shipping Method Text fields
  
  @IBOutlet weak var shippingMethodTextfield: UITextField!
  @IBOutlet weak var shippingMethodPicker: UIPickerView!
  
  // MARK: Expiration Date Text fields
  
  @IBOutlet weak var expirationDateTextfield: UITextField!
  @IBOutlet weak var expirationDatePicker: UIDatePicker!
  
  @IBOutlet weak var billingAddressSwitch: UISwitch!
  
  @IBAction func expirationDatePickerValueChange(_ sender: UIDatePicker) {
    let date = sender.date
    let request = CreateOrder.FormatExpirationDate.Request(date: date)
    interactor?.formatExpirationDate(request)
  }
  
  @IBAction func createOrder(_ sender: UIBarButtonItem) {
    
  }
  
  // MARK: Display Logic
  func displayExpirationDate(_ viewModel: CreateOrder.FormatExpirationDate.ViewModel) {
    expirationDateTextfield.text = viewModel.date
  }
}

extension CreateOrderViewController: UIPickerViewDelegate & UIPickerViewDataSource {
  func numberOfComponents(in pickerView: UIPickerView) -> Int {
    return 1
  }
  
  func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
    return interactor?.shipmentMethods.count ?? 0
  }
  
  func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
    return interactor?.shipmentMethods[row]
  }
  
  func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
    shippingMethodTextfield.text = interactor?.shipmentMethods[row]
  }
}

extension CreateOrderViewController {
  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    guard let cell = tableView.cellForRow(at: indexPath) else { return }
    
    for textField in textFields {
      if textField.isDescendant(of: cell) {
        textField.becomeFirstResponder()
      }
    }
  }
}

extension CreateOrderViewController: UITextFieldDelegate {
  func textFieldShouldReturn(_ textField: UITextField) -> Bool {
    textField.resignFirstResponder()
    if let index = textFields.firstIndex(of: textField) {
      if index < textFields.count - 1 {
        let nextTextfield = textFields[index + 1]
        nextTextfield.becomeFirstResponder()
      }
    }
    
    return true
  }
}
