//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/25/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
  enum FormatExpirationDate
  {
    struct Request
    {
      var date: Date
    }
    
    struct Response {
      var date: Date
    }
    
    struct ViewModel {
      var date: String
    }
  }
}
