//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by Yingzheng Ma on 1/25/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderBusinessLogic
{
  var shipmentMethods: [String] { get }
  func formatExpirationDate(_ request: CreateOrder.FormatExpirationDate.Request)
}

protocol CreateOrderDataStore
{
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore
{
  var presenter: CreateOrderPresentationLogic?
  var worker: CreateOrderWorker?
  var shipmentMethods: [String] = [
    "Standard Shipping",
    "Two-Day Shipping",
    "One-Day Shipping"
  ]
  
  func formatExpirationDate(_ request: CreateOrder.FormatExpirationDate.Request) {
    let response = CreateOrder.FormatExpirationDate.Response(date: request.date)
    presenter?.presentExpirationDate(response)
  }
}
