//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by Ma, Yingzheng (Y.) on 2/5/19.
//  Copyright (c) 2019 Yingzheng Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderBusinessLogic
{
  func getOrder(request: ShowOrder.GetOrder.Request)
}

protocol ShowOrderDataStore
{
  // we enable setter becuase it need to be populated when clicking an row on order list
  var order: Order! { get set }
}

class ShowOrderInteractor: ShowOrderBusinessLogic, ShowOrderDataStore
{
  var presenter: ShowOrderPresentationLogic?
  var order: Order!
  
  // MARK: Fetch Order
  
  func getOrder(request: ShowOrder.GetOrder.Request)
  {
    let response = ShowOrder.GetOrder.Response(order: order)
    presenter?.presentOrder(response: response)
  }
}
